// <auto-generated />
using System;
using BarraSuplementos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarraSuplementos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BarraSuplementos.Models.Carrinho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Carrinho");
                });

            modelBuilder.Entity("BarraSuplementos.Models.CarrinhoProduto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Qtd")
                        .HasColumnType("int");

                    b.Property<int?>("SaborId")
                        .HasColumnType("int");

                    b.HasKey("Id", "CarrinhoId");

                    b.HasIndex("CarrinhoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SaborId");

                    b.ToTable("CarrinhoProduto");
                });

            modelBuilder.Entity("BarraSuplementos.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Destaque")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destaque = false,
                            Nome = "Acessórios"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Os melhores suplementos para atingir seu objetivo de emagrecer.",
                            Destaque = true,
                            Imagem = "/img/emagrecerObjetivo_resized.jpg",
                            Nome = "Emagrecimento"
                        },
                        new
                        {
                            Id = 3,
                            Destaque = false,
                            Nome = "Energia e Resistência"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Os melhores suplementos para atingir seu objetivo de ganho de massa.",
                            Destaque = true,
                            Imagem = "img/ganhoMassa_resized (1).jpg",
                            Nome = "Massa Muscular"
                        },
                        new
                        {
                            Id = 5,
                            Destaque = false,
                            Nome = "Naturais"
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Os melhores suplementos para para atingir seu objetivo de definição.",
                            Destaque = true,
                            Imagem = "img/hipertrofia_resized.jpg",
                            Nome = "Pré/Pró Hormonal"
                        },
                        new
                        {
                            Id = 7,
                            Destaque = false,
                            Nome = "Vestuário"
                        },
                        new
                        {
                            Id = 8,
                            Destaque = false,
                            Nome = "Vitamas e Minerais"
                        });
                });

            modelBuilder.Entity("BarraSuplementos.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Marca");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Adaptogen"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Atlhetica Nutrition"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Bestronger"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Blackskull"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Darkness"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Dr. Peanut"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "FTW SPORTS NUTRITION"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Hopper"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Integralmédica"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Max Titanium"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Nitromax"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Nutrivale"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Orion Supplements"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Puritans Pride"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Rock"
                        },
                        new
                        {
                            Id = 16,
                            Nome = "Shark Pro"
                        },
                        new
                        {
                            Id = 17,
                            Nome = "SUDRACT"
                        });
                });

            modelBuilder.Entity("BarraSuplementos.Models.Objetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Objetivo");
                });

            modelBuilder.Entity("BarraSuplementos.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Imagem")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Lancamento")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("QtdEstoque")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 6328,
                            CategoriaId = 1,
                            Descricao = "600ml, polipropileno (BPA), matéria-prima atóxica, livre de Bisfenol A e Ftalato (DEHP) COR: PRETA",
                            Imagem = "img/produtos/1.png",
                            Lancamento = true,
                            MarcaId = 4,
                            Nome = "Coqueteleira - BLACKSKULL",
                            QtdEstoque = 67,
                            ValorAtual = 19.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006583,
                            CategoriaId = 1,
                            Descricao = "- Odor Free. - Antivazamento.- 600ml. ",
                            Imagem = "img/produtos/2.png",
                            Lancamento = true,
                            MarcaId = 1,
                            Nome = "Coqueteleira - FTW",
                            QtdEstoque = 36,
                            ValorAtual = 19.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 6098,
                            CategoriaId = 1,
                            Descricao = "O Strap Monster Be Stronger é um acessório essencial pra você amador e profissional da musculação, cross training, powerlifting, bodybuilding e weightlifting!",
                            Imagem = "img/produtos/3.png",
                            Lancamento = true,
                            MarcaId = 3,
                            Nome = "Strap monster - BESTRONGER",
                            QtdEstoque = 24,
                            ValorAtual = 69.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006531,
                            CategoriaId = 1,
                            Descricao = "Antivazamento.- 600ml. ",
                            Imagem = "img/produtos/4.jpg",
                            Lancamento = true,
                            MarcaId = 9,
                            Nome = "Coqueteleira com mola - INTEGRALMÉDICA",
                            QtdEstoque = 17,
                            ValorAtual = 24.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006518,
                            CategoriaId = 2,
                            Descricao = "O Therma Pro Hardcore é um termogênico que fornece 280 mg de cafeína, ótima opção para aumentar a energia e queimar gordura.",
                            Imagem = "img/produtos/5.jpg",
                            Lancamento = false,
                            MarcaId = 9,
                            Nome = "Therma Pro Hardcore 60caps - INTEGRALMÉDICA",
                            QtdEstoque = 8,
                            ValorAtual = 69.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006940,
                            CategoriaId = 2,
                            Descricao = "Apresentação: Pote com 60 cápsulas. Ingredientes: Picolinato de cromo, estabilizantes celulose microcristalina e amido, antiumectante dióxido de silício. Ingredientes da cápsula: Gelatina, opacificante dióxido de titânio e água potável filtrada.",
                            Imagem = "img/produtos/6.jpg",
                            Lancamento = false,
                            MarcaId = 7,
                            Nome = "Picolinato de Cromo 60caps - FTW SPORTS NUTRITION",
                            QtdEstoque = 7,
                            ValorAtual = 59.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 6472,
                            CategoriaId = 2,
                            Descricao = "O Diabo Verde é um pré-treino em cápsulas para atletas a base de cafeína que atua no aumento da capacidade de resistência e no desempenho de exercícios físicos.",
                            Imagem = "img/produtos/7.jpg",
                            Lancamento = false,
                            MarcaId = 7,
                            Nome = "Thermo CAPS 60caps - DIABO VERDE FTW",
                            QtdEstoque = 7,
                            ValorAtual = 74.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006987,
                            CategoriaId = 2,
                            Descricao = "O THERMO FLAME entrega 360mg de cafeína pura por dose, proporcionando mais energia e foco, otimizando os resultados na busca pelo emagrecimento.",
                            Imagem = "img/produtos/8.jpg",
                            Lancamento = false,
                            MarcaId = 11,
                            Nome = "Thermoflame 60caps - BLACKSKULL",
                            QtdEstoque = 6,
                            ValorAtual = 59.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 6228,
                            CategoriaId = 2,
                            Descricao = "NITRO FIRE 420mg é um suplemento a base de cafeína. Sua fórmula exclusiva além de dar um ânimo de imediato e duradouro, aumenta a termogênese do atleta!",
                            Imagem = "img/produtos/9.jpg",
                            Lancamento = false,
                            MarcaId = 11,
                            Nome = "Termogêmico Nitrofire 60caps - NITROMAX",
                            QtdEstoque = 1,
                            ValorAtual = 65m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007058,
                            CategoriaId = 3,
                            Descricao = "omos conhecidos por nosso sabor inigualável e agora realizamos o sonho de todos os amantes de alfajor com nossa versão dessa maravilha. Composta por duas camadas de leves e crocantes bolachas, recheadas com a famosa pasta de amendoim Dr. Peanut e cobertas com chocolate zero açúcar. Sabor e textura inconfundíveis, com ingredientes de altíssima qualidade. Experimente! ",
                            Imagem = "img/produtos/10.jpg",
                            Lancamento = false,
                            MarcaId = 6,
                            Nome = "Alfajor Avelã 55g - DR. PEANUT",
                            QtdEstoque = 52,
                            ValorAtual = 12.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007055,
                            CategoriaId = 3,
                            Descricao = "Somos conhecidos por nosso sabor inigualável e agora realizamos o sonho de todos os amantes de alfajor lançando nossa versão dessa maravilha. Composta por duas camadas de leves e crocantes bolachas, recheadas com a famosa pasta de amendoim Dr. Peanut e cobertas com chocolate zero açúcar. Sabor e textura inconfundíveis com ingredientes de altíssima qualidade. Experimente!",
                            Imagem = "img/produtos/11.jpg",
                            Lancamento = false,
                            MarcaId = 6,
                            Nome = "Alfajor Chocolante Branco 55g - DR. PEANUT",
                            QtdEstoque = 39,
                            ValorAtual = 12.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006966,
                            CategoriaId = 3,
                            Descricao = "Quem é #DoctorLover de verdade sabe que essa é uma das queridinhas, né! A combinação perfeita da pasta de amendoim com chocolate, avelã e wafer, sem adição de açúcar e zero glúten só poderia resultar nessa delícia. Garanta já a sua e leve esse sabor especial para o seu dia a dia mais saudável!",
                            Imagem = "img/produtos/12.jpg",
                            Lancamento = false,
                            MarcaId = 6,
                            Nome = "Dr Peanut Buenissimo 600g - DR. PEANUT",
                            QtdEstoque = 36,
                            ValorAtual = 59.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007074,
                            CategoriaId = 3,
                            Descricao = "Como preparar: diluir 20g (uma colher de sopa) do produto em 500ml de água gelada, mexer até que o produto se dissolva e estará pronto para o consumo; indicados para adultos praticantes de atividade. Repõe os eletrólitos perdidos no suor; - evita câimbras e desidratação; - melhor desempenho; - baixa caloria",
                            Imagem = "img/produtos/13.jpg",
                            Lancamento = false,
                            MarcaId = 17,
                            Nome = "Hydramaxi Morango com maracujá 20g - SUDRACT",
                            QtdEstoque = 17,
                            ValorAtual = 3.95m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006972,
                            CategoriaId = 3,
                            Descricao = "Aquele sabor de infância que só a Doctor Leite em Pó pode te proporcionar! Aliada e coringa de todas as refeições, além de ter zero adição de açúcar e zero glúten, essa delícia é perfeita para o seu dia a dia. Desde o café da manhã mais completo, até um lanchinho rápido e saudável, esse sabor vai te conquistar",
                            Imagem = "img/produtos/14.jpg",
                            Lancamento = false,
                            MarcaId = 6,
                            Nome = "Dr Peanut Leite em pó 600g - DR. PEANUT",
                            QtdEstoque = 10,
                            ValorAtual = 79.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006951,
                            CategoriaId = 3,
                            Descricao = "O que é o #Dilabol Black da FTW? Cada substância escolhida para o #Dilabol Black Diabo Verde foi pensada exclusivamente para o melhor desempenho das vias metabólicas do nosso organismo a combinação perfeita para o seu treino Hard!",
                            Imagem = "img/produtos/15.jpg",
                            Lancamento = false,
                            MarcaId = 7,
                            Nome = "Dilabol Black 120caps - FTW SPORTS NUTRITION",
                            QtdEstoque = 8,
                            ValorAtual = 99.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006971,
                            CategoriaId = 3,
                            Descricao = "Essa é a pasta de amendoim dos seus sonhos, com o sabor irresistível de Avelã! Nossa receita faz com que ela seja incrivelmente cremosa, deliciosamente saborosa e perfeita para uma alimentação saudável. Feita com ingredientes de alta qualidade, sem adição de açúcar e sem glúten, cada colherada é uma explosão de sabores, com a combinação perfeita de amendoim e avelã. Experimente, seu lanche nunca mais será o mesmo! ",
                            Imagem = "img/produtos/16.jpg",
                            Lancamento = false,
                            MarcaId = 6,
                            Nome = "Dr Peanut Avelã 600g - DR. PEANUT",
                            QtdEstoque = 8,
                            ValorAtual = 59.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006545,
                            CategoriaId = 4,
                            Descricao = "A Cindy Bar sabor Doce de Coco, da Hopper, é uma barrinha que fornece 13 g de proteínas de alto valor biológico, com adição de TCM, carboidratos de baixo índice glicêmico além de um mix de vitaminas e minerais.",
                            Imagem = "img/produtos/17.jpg",
                            Lancamento = false,
                            MarcaId = 8,
                            Nome = "Cindy Bar Doce de coco 45g - HOPPER",
                            QtdEstoque = 96,
                            ValorAtual = 9.50m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007039,
                            CategoriaId = 4,
                            Descricao = "O que é 100% Whey Protein Apresenta variedade e praticidade em um só produto. Praticantes de atividade física ou quem busca uma rotina alimentar com bons nutrientes se beneficia do uso das proteínas do soro do leite, que fornecem qualidade nutricional com alto valor biológico. Contém grande concentração de proteínas e aminoácidos (rico em Bcaas e Glutamina) que são essenciais para os processos de ganho, recuperação e manutenção muscular. ",
                            Imagem = "img/produtos/18.jpg",
                            Lancamento = false,
                            MarcaId = 7,
                            Nome = "Whey Ftw 100% Cookies 900g refil - FTW",
                            QtdEstoque = 96,
                            ValorAtual = 149.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007036,
                            CategoriaId = 4,
                            Descricao = "O que é 100% Whey Protein Apresenta variedade e praticidade em um só produto. Praticantes de atividade física ou quem busca uma rotina alimentar com bons nutrientes se beneficia do uso das proteínas do soro do leite, que fornecem qualidade nutricional com alto valor biológico. Contém grande concentração de proteínas e aminoácidos (rico em Bcaas e Glutamina) que são essenciais para os processos de ganho, recuperação e manutenção muscular. ",
                            Imagem = "img/produtos/19.jpg",
                            Lancamento = false,
                            MarcaId = 7,
                            Nome = "Whey Ftw 100% Chocolate 900g refil - FTW",
                            QtdEstoque = 87,
                            ValorAtual = 149.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006499,
                            CategoriaId = 4,
                            Descricao = "Proteína e Emagrecimento A proteína é um nutriente que nos traz sensação de saciedade. No emagrecimento, o lanche rico em proteína irá auxiliar o controle da ingestão entre as refeições. Para quem visa o ganho de massa muscular, colocar proteína nos lanches é uma excelente estratégia para o consumo da necessidade proteica diária e, as barrinhas trazem muita praticidade e sabor!",
                            Imagem = "img/produtos/20.jpg",
                            Lancamento = false,
                            MarcaId = 10,
                            Nome = "Top Whey Bar Brigadeiro 41g - MAX TITANIUM",
                            QtdEstoque = 86,
                            ValorAtual = 8m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006498,
                            CategoriaId = 4,
                            Descricao = "Proteína e Emagrecimento A proteína é um nutriente que nos traz sensação de saciedade. No emagrecimento, o lanche rico em proteína irá auxiliar o controle da ingestão entre as refeições. Para quem visa o ganho de massa muscular, colocar proteína nos lanches é uma excelente estratégia para o consumo da necessidade proteica diária e, as barrinhas trazem muita praticidade e sabor!",
                            Imagem = "img/produtos/21.jpg",
                            Lancamento = false,
                            MarcaId = 10,
                            Nome = "Top Whey Bar Chocolate com Avelã 41g - MAX TITANIUM",
                            QtdEstoque = 82,
                            ValorAtual = 8m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007037,
                            CategoriaId = 4,
                            Descricao = "O que é 100% Whey Protein Apresenta variedade e praticidade em um só produto. Praticantes de atividade física ou quem busca uma rotina alimentar com bons nutrientes se beneficia do uso das proteínas do soro do leite, que fornecem qualidade nutricional com alto valor biológico. Contém grande concentração de proteínas e aminoácidos (rico em Bcaas e Glutamina) que são essenciais para os processos de ganho, recuperação e manutenção muscular. ",
                            Imagem = "img/produtos/22.jpg",
                            Lancamento = false,
                            MarcaId = 7,
                            Nome = "Whey Ftw 100% Morango 900g refil - FTW",
                            QtdEstoque = 63,
                            ValorAtual = 149.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006959,
                            CategoriaId = 4,
                            Descricao = "Aumento de força muscular; Ganho de massa muscular; Aumento na saciedade; Recuperação muscular; Energia",
                            Imagem = "img/produtos/23.jpg",
                            Lancamento = false,
                            MarcaId = 5,
                            Nome = "Dark Bar Creme de coco com castanha 90G -  DARKNESS",
                            QtdEstoque = 56,
                            ValorAtual = 16.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006621,
                            CategoriaId = 4,
                            Descricao = "A Protein Crisp é formada por 13g proteínas de alto valor biológico. Essas proteínas são fundamentais para a construção de muscular, além de serem importantes para a manutenção da massa muscular em programas de perda de peso. Por isso a Protein Crisp pode ser consumida tanto em dietas para perda de peso, quanto em dietas para ganho de massa muscular. Por ser uma barra de proteína completa, com proteínas, gorduras essenciais e aminoácidos, sua ingestão aumenta a saciedade entre as refeições, diminuindo a vontade de comer doces e alimentos calóricos.",
                            Imagem = "img/produtos/24.jpg",
                            Lancamento = false,
                            MarcaId = 9,
                            Nome = "CRISP BAR Duo Crunch 45g - INTEGRALMÉDICA",
                            QtdEstoque = 50,
                            ValorAtual = 8m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 32,
                            CategoriaId = 4,
                            Descricao = "Ganhe volume e massa muscular, aumente sua força e melhore o desempenho e resistência nos seus treinos suplementando com a Creatina Hardcore Integralmédica. Produto 100% puro, de excelente qualidade.",
                            Imagem = "img/produtos/25.jpg",
                            Lancamento = false,
                            MarcaId = 9,
                            Nome = "Creatina 300g - INTEGRALMÉDICA",
                            QtdEstoque = 49,
                            ValorAtual = 149.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1006622,
                            CategoriaId = 4,
                            Descricao = "O Cracker Monster ROCK é um saboroso e delicioso cracker, coberto com chocolate e recheado com a Pasta de Amendoim Branco ROCK, tudo isso ZERO açúcar, com proteína WheyRock, ótimo valor nutricional e sabor totalmente insano",
                            Imagem = "img/produtos/26.jpg",
                            Lancamento = false,
                            MarcaId = 15,
                            Nome = "Cracker Monster Chocolate Branco - ROCK",
                            QtdEstoque = 44,
                            ValorAtual = 6.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007107,
                            CategoriaId = 4,
                            Descricao = "Potencialize Seu Desempenho Nossa Energy Creatina é a aliada perfeita para impulsionar seu desempenho atlético e alcançar novos patamares nos treinos. Sendo monohidratada e saborosa, essa creatina em pó é ideal para quem busca resultados eficazes e uma experiência saborosa. Com uma fórmula de alta qualidade, a Energy Creatina fornece a dose necessária desse poderoso suplemento alimentar, contribuindo para aumentar a força, a resistência e a recuperação muscular.",
                            Imagem = "img/produtos/27.jpg",
                            Lancamento = false,
                            MarcaId = 16,
                            Nome = "Creatina 300g - SHARK PRO",
                            QtdEstoque = 42,
                            ValorAtual = 119.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 6414,
                            CategoriaId = 5,
                            Descricao = "Nutrientes essenciais utilizados como combustíveis para as células e uma das fontes de energia, os ácidos graxos não são produzidos pelo corpo, mas são muito importantes para nosso organismo. O ômega 3 é um ácido graxo e pode ser encontrado em peixes de água fria ou suplementos alimentares de forma concentrada e pura.",
                            Imagem = "img/produtos/28.jpg",
                            Lancamento = false,
                            MarcaId = 2,
                            Nome = "Ômega 3 60caps - ATLHETICA NUTRITION",
                            QtdEstoque = 2,
                            ValorAtual = 39.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007093,
                            CategoriaId = 6,
                            Descricao = "O Tribulus Terrestris Gold da Orion Supplements é um suplemento nutricional formulado para ajudar a aumentar a energia, a resistência e a força física. A fórmula avançada combina os benefícios do Tribulus Terrestris com outros ingredientes naturais cuidadosamente selecionados para ajudar a melhorar o desempenho físico e sexual.",
                            Imagem = "img/produtos/29.jpg",
                            Lancamento = false,
                            MarcaId = 13,
                            Nome = "Tribulus GOLD 90caps - ORION SUPPLEMENTS",
                            QtdEstoque = 4,
                            ValorAtual = 167m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 6344,
                            CategoriaId = 7,
                            Descricao = "A Regata Preta Basquete Max Titanium - Edição Limitada é uma opção moderna e estilosa para quem pratica esportes, oferecendo conforto e liberdade de movimento.",
                            Imagem = "img/produtos/30.jpg",
                            Lancamento = false,
                            MarcaId = 10,
                            Nome = "Camisa / Regata - MAX TITANIUM",
                            QtdEstoque = 14,
                            ValorAtual = 49.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 268,
                            CategoriaId = 8,
                            Descricao = "APRESENTAÇÃO: Pote com 60 cápsulas. INGREDIENTES: Acetato de retinol, picolinato de cromo, bisglicinato de cobre, tiamina mononitrato, riboflavina, cloridrato piridoxina, cianocobalamina, ácido ascórbico, vitamina D3 (colecalciferol), acetato de tocoferol, nicotinamida, pantotenato de cálcio, sulfato de manganês, sulfato de zinco, óxido de magnésio, estabilizantes celulose microcristalina e amido de milho e antiumectante dióxido de silício.",
                            Imagem = "img/produtos/31.jpg",
                            Lancamento = false,
                            MarcaId = 7,
                            Nome = "Multivitaminico 60caps - FTW",
                            QtdEstoque = 22,
                            ValorAtual = 24.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007005,
                            CategoriaId = 8,
                            Descricao = "4-SLEEP possui a combinação de quatro compostos ativos que em conjunto atuam na indução do sono mais profundo e reparador",
                            Imagem = "img/produtos/32.jpg",
                            Lancamento = false,
                            MarcaId = 12,
                            Nome = "4 Sleep 90caps - INTEGRALMÉDICA",
                            QtdEstoque = 2,
                            ValorAtual = 69.90m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007094,
                            CategoriaId = 8,
                            Descricao = "Melatonina 3mg GNC  é um suplemento ideal para pessoas que possuem dificuldades para dormir ou que querem melhorar ainda mais a qualidade do sono. Com a Melatonina é possível dormir menos horas e melhor, pois a melatonina vai te levar ao sono REM mais rapidamente. É impressionante como acordamos melhor ao utilizar a melatonina logo antes de dormir. A melatonina é um hormônio natural que o seu corpo já produz, portanto é 100% seguro o uso deste produto.",
                            Imagem = "img/produtos/33.jpg",
                            Lancamento = false,
                            MarcaId = 12,
                            Nome = "Melatonina 120caps - GNC",
                            QtdEstoque = 2,
                            ValorAtual = 140m,
                            ValorDesconto = 0m
                        },
                        new
                        {
                            Id = 1007095,
                            CategoriaId = 8,
                            Descricao = "O que é 5-HTP? O aminoácido 5-HTP — também conhecido como 5-hidroxitriptofano — vai agir no cérebro e no sistema nervoso central como ator principal para a formação de serotonina, aumentando sua produção.",
                            Imagem = "img/produtos/34.jpg",
                            Lancamento = false,
                            MarcaId = 14,
                            Nome = "5-HTP 60Caps - PURITANS PRIDE",
                            QtdEstoque = 1,
                            ValorAtual = 180m,
                            ValorDesconto = 0m
                        });
                });

            modelBuilder.Entity("BarraSuplementos.Models.ProdutoObjetivo", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("ProdutoId", "ObjetivoId");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("ProdutoObjetivo");
                });

            modelBuilder.Entity("BarraSuplementos.Models.ProdutoSabor", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("SaborId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("ProdutoId", "SaborId");

                    b.HasIndex("SaborId");

                    b.ToTable("ProdutoSabor");
                });

            modelBuilder.Entity("BarraSuplementos.Models.Sabor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Sabor");
                });

            modelBuilder.Entity("BarraSuplementos.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Foto")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = "66f78b3c-cea0-47b3-a8c5-04802a596522",
                            DataNascimento = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Foto = "/img/usuarios/avatar.png",
                            Nome = "José Roberto Grigolato"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "90901a72-ed64-4aa6-8d34-813e48389081",
                            ConcurrencyStamp = "62f0e9c2-1c1a-449f-b2a3-127bb0e705ad",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "9b5190b6-918d-458d-9473-c4cf0fdf6ff0",
                            ConcurrencyStamp = "e85e4929-790a-4812-9bbb-2c03723a90aa",
                            Name = "Funcionário",
                            NormalizedName = "FUNCIONARIO"
                        },
                        new
                        {
                            Id = "67b86261-6ba0-4888-863e-c506d5ff0522",
                            ConcurrencyStamp = "23a8757d-06e6-4c5b-a57e-ff0c1d792d9c",
                            Name = "Cliente",
                            NormalizedName = "CLIENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "66f78b3c-cea0-47b3-a8c5-04802a596522",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "39c970d4-6079-4ff1-b878-d09f9fe96726",
                            Email = "admin@barrasuplementos.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BARRASUPLEMENTOS.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAELZIdDj5xiuasbSHGY4plipFhmpu0nwWAggOmXp3o/JPZ7UjFgzNF3bC0s34gNJqOg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9940f935-751d-42ea-b375-1e3d5376b782",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "66f78b3c-cea0-47b3-a8c5-04802a596522",
                            RoleId = "90901a72-ed64-4aa6-8d34-813e48389081"
                        },
                        new
                        {
                            UserId = "66f78b3c-cea0-47b3-a8c5-04802a596522",
                            RoleId = "9b5190b6-918d-458d-9473-c4cf0fdf6ff0"
                        },
                        new
                        {
                            UserId = "66f78b3c-cea0-47b3-a8c5-04802a596522",
                            RoleId = "67b86261-6ba0-4888-863e-c506d5ff0522"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BarraSuplementos.Models.Carrinho", b =>
                {
                    b.HasOne("BarraSuplementos.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BarraSuplementos.Models.CarrinhoProduto", b =>
                {
                    b.HasOne("BarraSuplementos.Models.Carrinho", "Carrinho")
                        .WithMany("Produtos")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarraSuplementos.Models.Produto", "Produto")
                        .WithMany("Carrinhos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarraSuplementos.Models.Sabor", "Sabor")
                        .WithMany("Carrinhos")
                        .HasForeignKey("SaborId");

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");

                    b.Navigation("Sabor");
                });

            modelBuilder.Entity("BarraSuplementos.Models.Produto", b =>
                {
                    b.HasOne("BarraSuplementos.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarraSuplementos.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("BarraSuplementos.Models.ProdutoObjetivo", b =>
                {
                    b.HasOne("BarraSuplementos.Models.Objetivo", "Objetivo")
                        .WithMany("Produtos")
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarraSuplementos.Models.Produto", "Produto")
                        .WithMany("Objetivos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objetivo");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("BarraSuplementos.Models.ProdutoSabor", b =>
                {
                    b.HasOne("BarraSuplementos.Models.Produto", "Produto")
                        .WithMany("Sabores")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarraSuplementos.Models.Sabor", "Sabor")
                        .WithMany("Produtos")
                        .HasForeignKey("SaborId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Sabor");
                });

            modelBuilder.Entity("BarraSuplementos.Models.Usuario", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "ContaUsuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaUsuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarraSuplementos.Models.Carrinho", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("BarraSuplementos.Models.Objetivo", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("BarraSuplementos.Models.Produto", b =>
                {
                    b.Navigation("Carrinhos");

                    b.Navigation("Objetivos");

                    b.Navigation("Sabores");
                });

            modelBuilder.Entity("BarraSuplementos.Models.Sabor", b =>
                {
                    b.Navigation("Carrinhos");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
